# Generated by Django 5.1.7 on 2025-04-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123456, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
