# Generated by Django 5.1.7 on 2025-05-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_user',
            new_name='doctor_user_id',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_user',
            new_name='patient_user_id',
        ),
    ]
