# Generated by Django 5.1.7 on 2025-05-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_user_is_phone_verified_user_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default='false'),
        ),
    ]
