# Generated by Django 5.1.7 on 2025-05-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
