# Generated by Django 5.1.7 on 2025-05-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_user_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
