# Generated by Django 5.1.7 on 2025-05-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_user_last_login_alter_user_password_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
