# Generated by Django 5.1.7 on 2025-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_user_gmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
